### ISSUE TITLE
Get Reek working in circleci

### ISSUE THREAD

**Issue by ketiko** [ketiko-labs/budget#4]
```====>> Reek
  #!/bin/bash -eo pipefail
bin/reek -n --sort-by smelliness
Inspecting 7865 file(s):
.......SSSSSSSSSSSSSSSSS.SSSSSSSS.SSSSSSSSSSSSSSS..SSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSS..SSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSS.SSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSS.SSS.SSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..SSSSSSSSS.SSSSSSSSSSSSSSSSS..SSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSS.SSSSSSSSSSSSSSSSSS..S.S.S.SSSSS.SSSSSSSS.SSS.SSSSSSSSS.SSS.SSSS.SSSSSS.SSSSSS.SSSSS.SS.SSSSS.SSS.SSSS.SSSSSSSSSSSSSSS.SSSSS.S..SSSSSSSSSSSSSSSSSSSS.S.SSS.SS.SSSSSSSSSSSSSSSSSSSSSSSSSSSS.S.SSSSSSSSS.SSS.SSSSSSSSSSSSSSSSSS.S...SSSSSSS.SSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SS.SSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSS.S..SSS..SS..SS............S.SS..SS.SSSSSSSSSSSSSSSSSSSSSSSSSS..SS.....SSS..SSSSSSSSSS.S.S...S.S......SS..S...........................................SSS.S.....S..SSSSSSSSS.SSSSSSSS.SS.S.S..............SSSSSS...SSSSSSSSSSSSSSSS.SSSSS.SSSS.SS.........S...S..SSSSSSSSSSSSS.SSSSSSSSSSSSSSSS.SSSSSSSSSS..S..........SSSSS.SSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..SSSSSSSSS.S..SS.S.....S...SSSSS.SSSSSSSS.SSSS.SSSSSSS.SSSSS.S.SSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSS.SSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.S........S..SSS.SSSSSSSSSSS..S.SSS.SS....SSSS.SSSS.SSSS..SSSSSSSSSSSSSSSSSSSSSSSSS.SS.SS.........SSSSS.S.S..SSSS.SSSSSS.S.SSS..SSSSSSSSSSSSSS.SS.S.S.........S.....SSS.SS..S.S.SSSSS..SSSSSSSS.SSSSSSSSSSSSSSSSSSSSS.SSSSSSS.S.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...SS.SSSSSSSSSSSSS.SSSS.SSSSSSSSSSSSSSSSS.SSSSS.SSSSSSS.SSSSSSS.SSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSS..SSSS.S.SSSSSSS.SS......SSSSS........S.SSS.SSSSSSSS.SSSSS.SSSSSSS.S.SSSSSS.SSSSSSS..SSS.SSSS..S.S....SSSSSSSS.SSSSSSS..SSSSSS...SSSSSS......S.S..........SSSSSSSSSSSSSSSSS...SSSSS..SSSSS....SSSS.S..S.S...SSSSSSSSSSSSSSSSS.SSSSSSSS.SS..S....S..........SSS.SS.SSSSSS.SS..SSSSSSSSSSSSSSSSSSSSSSSSS.SS.SSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSS...SSS.SSSS.SS..SSS.SSSSSSSSS..SSS..................................................................................SSS..S.SSSSSSSSSSSSSSSSSSSSSSSS....SS...SSSS.SSSSSSSS.S.SS.SSSSS..SSSSSSSS.S.SSSS.SSSSSSSSS.SSSSSSSSS.SSSSSSSS..SSSSSSSS.SSSSSSSSS...S.....SSSSSSSSSSSSSSSSSSS........SSSSSSSSSSSSSS.SSS..SSSSSS.SSSSSSS.SSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SS.SSSS.SSSSSSSSSSS..........S.SSSSSS.SSSSSSS.S.S.SSSSSSSS.........S...SS..SS.SS.S.S..S.S....SSSSSSSSSSSSSSSSSSSSSSSSSSS.SSS.........SS..S......SSSSSSSSSSSS..S.SSSSSSS.SSSS.SSSSSSSSSSSSSSSSSS.SSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSS..SSSS.S.SSSS.SSSSSSSSS.SSSSSSS.SSSSSSSSS.SSSS...S...SSSSSSSS.......SS..................S...SSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSS....SSS.S..S...SS.SSSSSSSSSSSS..SS.SSS.SS.SS.SSSSS.SSS.SSSS.SS.SSSSSS..SS....SS.SSS..SSSS.SSSS.SSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSS.SSSSS.S....SS.SSS...SSS..........SSSSSSSSSSSSS.S.SS....S.....S....S.SS.S.....S.S...SSSSSSSSSSSSSSSSSSSSSSSSSSSSS.S.S..S.S.S..SSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..SS.........S..S...S.................S..............SS.S.S.S.......SS.SSSSSSSSSSSSSSSSS.SSSSSSSSS.SS..S...SSS....SS..SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSS.SSSSSSS.S.SSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSS........S........S.SSSSSSSS.SSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSS.
SSSSSSSSSSSSSSSSSSSSSSSS.S..SSSSS.SSSSSSS....SSSS..SS..SSSSSSSSS.S.SSS.SSSSSSSSSSSSSSSS..SSSSSSSSSSSS.SSSSSSSSSSSSSS.SSS        !!!
        Source vendor/bundle/ruby/2.4.0/gems/nested_form-0.3.2/lib/nested_form/builders.rb can not be processed by Reek.

        This is most likely either a bug in your Reek configuration (config file or
        source code comments) or a Reek bug.

        Please double check your Reek configuration taking the original exception
        below into account -  you might have misspelled a smell detector for instance.
        (In the future Reek will handle configuration errors more gracefully, something
        we are working on already).

        If you feel that this is not a problem with your Reek configuration but with
        Reek itself it would be great if you could report this back to the Reek
        team by opening up a corresponding issue at https://github.com/troessner/reek/issues.

        Please make sure to include the source in question, the Reek version
        and the original exception below.

        Exception message:

        undefined method `name' for #<#<Class:0x00000040800558>:0x000000407fe988>

        Original exception:

        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/smell_detectors/subclassed_from_core_class.rb:34:in `sniff'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/smell_detectors/base_detector.rb:44:in `run'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/detector_repository.rb:43:in `block in examine'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/detector_repository.rb:41:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/detector_repository.rb:41:in `flat_map'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/detector_repository.rb:41:in `examine'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:118:in `block in examine_tree'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:57:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:59:in `block in each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:58:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:58:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:59:in `block in each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:58:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:58:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:117:in `flat_map'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:117:in `examine_tree'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:102:in `run'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:67:in `smells'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:83:in `smelly?'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/report/formatter/progress_formatter.rb:44:in `progress'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/report/text_report.rb:22:in `add_examiner'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:17:in `execute'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/application.rb:29:in `execute'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/bin/reek:14:in `<top (required)>'
        bin/reek:18:in `load'
        bin/reek:18:in `<main>'

        !!!
.SS..SS.SSSSSSS............SSS.SS.S...SSS.SSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.S.SSSSSSSSSS.SSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSS.SS....SSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSS.SSSSSSSSSSSSSSS..SSSSSS.SSS.SS....S.SSSSSSSSS.S.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSS.SSSSSS..SSS.SSSSSSSSS.SSSS.SS.SSSS....S.SSS..........S.SSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSS.SSSSSSS.SSSSSSSS.SSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSS.SSSSSS..SSSSS.S..S.SSS.SSS...SS..S.SSSS.SSSSSSSSS.S.S..SSSSS.SSSSSSSSSSS.S.SSSSSSSS.S.SSSSSSSS.SSSSSSSSSSSS.SSSS............        !!!
        Source vendor/bundle/ruby/2.4.0/gems/paper_trail-7.1.0/spec/dummy_app/db/migrate/20110208155312_set_up_test_tables.rb can not be processed by Reek.

        This is most likely either a bug in your Reek configuration (config file or
        source code comments) or a Reek bug.

        Please double check your Reek configuration taking the original exception
        below into account -  you might have misspelled a smell detector for instance.
        (In the future Reek will handle configuration errors more gracefully, something
        we are working on already).

        If you feel that this is not a problem with your Reek configuration but with
        Reek itself it would be great if you could report this back to the Reek
        team by opening up a corresponding issue at https://github.com/troessner/reek/issues.

        Please make sure to include the source in question, the Reek version
        and the original exception below.

        Exception message:

        undefined method `name' for #<#<Class:0x00000029507d40>:0x00000029506c10>

        Original exception:

        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/smell_detectors/subclassed_from_core_class.rb:34:in `sniff'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/smell_detectors/base_detector.rb:44:in `run'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/detector_repository.rb:43:in `block in examine'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/detector_repository.rb:41:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/detector_repository.rb:41:in `flat_map'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/detector_repository.rb:41:in `examine'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:118:in `block in examine_tree'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:57:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:59:in `block in each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:58:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/context/code_context.rb:58:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:117:in `flat_map'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:117:in `examine_tree'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:102:in `run'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:67:in `smells'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:83:in `smelly?'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/report/formatter/progress_formatter.rb:44:in `progress'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/report/text_report.rb:22:in `add_examiner'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `each'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:17:in `execute'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/application.rb:29:in `execute'
        /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/bin/reek:14:in `<top (required)>'
        bin/reek:18:in `load'
        bin/reek:18:in `<main>'

        !!!
.............S..SSSS.....S...S.SS...SSS.SS..SSSS.S..SSS.SSSS..SSSSSSSSSS..SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..S..SS.SSSSSSSSSSSSSSSSSSSSS.SSSSSSSSS.S.SSS.SSSSSSSSS............................SS.SSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSS.SSSSSS.SSSSSSSSSS.SSSSSSSS.SSSSS..SS.........S...S..SSSSSS..SSS..S..SS....S.SSSSSSS.SSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSS.S..S.SSSSSSSSSSSSS.S.SSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..SSSS.SS.SSS.SSS.SS.SSSSSS..S..S.SS.SSSSSSS..SSSS..S..S...S..SSSSSSSSS.SSSSSS..SSSSSS..SS..SSSSSSSSSSSS...SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........SS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSS.....SSSSSSSSS.S.SS.S.S.SSSSSSS.SSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSS.SSSS.SSSSSSS.SSSSSSSSSSSSSS......S............SSSSSSSSSSSSSSSSSS..SSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSS.SSSSS.SS.SSSSSSSS.SSSSSSS.S.S.....S.SSSSSSSS.SSSSSS.SSSSSSSSSS.S.SSSS..SS.SS.SSSSSS..SS..SSS.S.S.....S.................................................................................................................................SS.SSSSSSSSS..................S............................................................SSSSS.SSSS.SS.SSSSSSSSSSSSSSS.S...SSSSSSSSSSSSSSSSSS.SSS.SSSSSSS.SSSSSSSSSSSSSSSSSSSS.SSSSSS.SS.S.SSSSSSSSSSS..SSSSSSSSSSSSSSSSSSSSSSSS.SSS.SSSS.SS.SSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSS.SSSSSS..SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSS.S....SSS...SSSSSSSSSS.S....SSS.SSSSSS.SSSSSSSSS.S.SSSSSS..SS.SSSSSS..SS..SSS...SSS..S.S.SSSSSSSSSSSSSSSSSSSSSSS.S.S.SSSSSSSSSSSS...SS.SSSSSSSSSSSSSSS.SS.SSSSSSSSSSSSSSSSSSSSSS.S.SSSSSSSSSSSSS.SSSS..S.S.SS..SS.SSSSSS.SSSSSSS.SSS.SSSSSS.SSSSSSS.SSSSS.S..SS.SSSSSSSS.S.SSS...SSSS.SSSSSSS.SSSSSSSSSSS.SSSSSSSS..SSSSSSSSSSSSSSS..SSS.S.SSSSSSS..SSSSSSSSSS.SS.SSSSSSSSS..SSSS....SSSS.SSSSS.SSS.S.SSS.SSSSS.SSS...SSSSSS.SS.SSSS.SSSSSS..S.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSS.SSSSSS.S.SSSSSSSSSSSSS..SSSSS.SSSSSSSSSSSSSSSSS.SSSSSSS.SSSSSS.SSSSSSS...SSSS.S...S..S...S.SS.SSSS.SSS...S.....S.S.SSSSSSS.......SS..SS.S............................................................SSSSSSSSSS.SSSS.SSSSSSS.S..SSSSSSSSSSSSSSSSS.SS.SSS.S...SSSSS.SSSSSSSSS.SSSS.SSSSSSS.SSSSS.S.SSSSSSSSSSSSSSSS.SSSSS.SSSSSSSSSSSS.SSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSS.S.S.S...S..S.SS..SSSS.SS..SSSSSSSS........SSSS.....SSS........SS/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/parser-2.4.0.0/lib/parser/source/buffer.rb:164:in `source=': invalid byte sequence in UTF-8 (EncodingError)
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/source/source_code.rb:99:in `parse'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/source/source_code.rb:33:in `initialize'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/source/source_code.rb:50:in `new'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/source/source_code.rb:50:in `from'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/examiner.rb:40:in `initialize'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `new'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `each'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:17:in `execute'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/lib/reek/cli/application.rb:29:in `execute'
        from /home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/reek-4.7.2/bin/reek:14:in `<top (required)>'
        from bin/reek:18:in `load'
        from bin/reek:18:in `<main>'
Error: Exited with code 1
```

**Comment by ketiko** [comment]
fixed
